# Site settings
name: Nolan
email: nolanjacobson@protonmail.com
#canonical_url: https://edwinexemplar.com
keywords: 'Software Engineer, Blockchain, Blockchain Developer, Smart Contracts, Smart Contract Developer, Startups, Agile, Hyperledger, React, React Native, C#, ASP.NET, JavaScript, Redux, Node, NodeJS, Express'
skills: 'Full Stack Blockchain Developer in Tampa, Florida'
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/nolanjacobson/
  - title: medium
    url: https://medium.com/@nolanjacobson
  - title: github
    url: https://github.com/nolanjacobson

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: '33, 150, 243'
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Build settings
markdown: kramdown
permalink: pretty
